dist: trusty

env:
  global:
    - CC_TEST_REPORTER_ID=a82fd111d71177b83059d5eaaf14e68438af425706069a325cc6d5fa8677ae3d

language: python

python:
  - "3.6"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libstdc++6-4.7-dev
  - curl -L https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.2-linux-x86_64.tar.gz > julia-0.6.2-linux-x86_64.tar.gz
  - tar xf julia-0.6.2-linux-x86_64.tar.gz
  - export PATH=$PATH:./julia-d386e40c17/bin/
  - chmod +x ./julia-d386e40c17/bin/julia

install:
  - python -m pip install -r requirements.txt
  - python -m pip install pytest coverage mock pytest-cov
  - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: pytest --runslow --cov=BondGraphTools --cov-report=xml test

after_script:
  ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT