dist: bionic

env:
  global:
    - CC_TEST_REPORTER_ID=895919e9413384a08a878a372ecad8e82ac0f6f80933e23cc36261e9986d27c0

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get install -y gfortran
  - curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > ./miniconda.sh
  - bash miniconda.sh -b -p miniconda
  - miniconda/bin/conda init
  - miniconda/bin/conda install -y -c conda-forge blas liblapack sundials

install:
  - python -m pip install -r requirements.txt
  - python -m pip install pytest==4.1.0 coverage==4.5.1 mock pytest-cov==2.6.1
  - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: pytest --runslow --cov=BondGraphTools --cov-report=xml test

after_script:
  ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
